---
version: 2
project_name: combo
universal_binaries:
  - replace: true
builds:
  -
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-s -w"
    main: ./cmd/combo
    mod_timestamp: "{{ .CommitTimestamp }}"
brews:
  -
    dependencies:
      -
        name: go
        type: build
    description: ""
    download_strategy: CurlDownloadStrategy
    directory: Formula
    homepage: "https://github.com/tolgaOzen/combo"
    license: "Apache-2.0"
    custom_block: |
      head "https://github.com/tolgaOzen/combo.git", :branch => "main"
    install: |-
        bin.install "combo"
    repository:
      name: combo-homebrew-tap
      owner: combo
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: permify-bot
      email: hello@permify.co
    url_template: "https://github.com/tolgaOzen/combo/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
nfpms:
  -
    description: "Combo is a CLI tool for managing Git workflows with AI."
    formats:
      - deb
      - rpm
      - apk
      - msi # Add MSI format here
    homepage: "https://github.com/tolgaOzen"
    license: "MIT"
    maintainer: "tolga <mtolgaozen@gmail.com>"
    vendor: "Tolga Ozen"
    contents:
      - src: "./dist/windows/amd64/combo.exe" # Path to the executable
        dst: "/Program Files/Combo/combo.exe" # Destination in the MSI
    msi:
      product_name: "Combo CLI"
      upgrade_code: "A2E6D8A1-5E84-4C5F-A9C6-F5BFE89775B3" # Unique GUID for upgrades
      manufacturer: "Tolga Ozen"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
checksum:
  name_template: checksums.txt
release:
  draft: true
  mode: replace
  prerelease: auto
  footer: |
    This version can be found as Docker images at tolgaOzen/combo:v{{ .Version }} and ghcr.io/tolgaOzen/combo:v{{ .Version }}.
