---
version: 2
project_name: combo
universal_binaries:
  - replace: true
builds:
  -
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-s -w"
    main: ./cmd/combo
    mod_timestamp: "{{ .CommitTimestamp }}"
brews:
  -
    dependencies:
      -
        name: go
        type: build
    description: ""
    download_strategy: CurlDownloadStrategy
    directory: Formula
    homepage: "https://github.com/tolgaOzen/combo"
    license: "MIT"
    install: |-
        bin.install "combo"
    repository:
      name: homebrew-tap-combo
      owner: tolgaOzen
      branch: main
    commit_author:
      name: tolgaOzen
      email: mtolgaozen@gmail.com
    url_template: "https://github.com/tolgaOzen/combo/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
nfpms:
  -
    description: "Combo is a CLI tool for managing Git workflows with AI."
    formats:
      - deb
      - rpm
      - apk
    homepage: "https://github.com/tolgaOzen"
    license: "MIT"
    maintainer: "tolga <mtolgaozen@gmail.com>"
    vendor: "Tolga Ozen"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
checksum:
  name_template: checksums.txt
release:
  draft: true
  mode: replace
  prerelease: auto
  footer: |
    This is an automated release.
