---
name: Release
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
  packages: write
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go
        with:
          go-version: ~1.23

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action
        with:
          distribution: goreleaser-pro
          version: ~> v2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
